<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPINHYDW0086" ignored="2" name="CalculatorTest" tests="32" failures="2" timestamp="13 Jun 2017 12:48:19 GMT" time="0.095" errors="0">
  <testcase name="testNegSub" time="0.005" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testCosine" time="0.005" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegSub" time="0.0" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegSub" time="0.002" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testAdd" time="0.002" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testAdd" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testAdd" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testCosine" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [-0.4480736161291702] but found [0.8939966636005579]">
      <![CDATA[java.lang.AssertionError: expected [-0.4480736161291702] but found [0.8939966636005579]
	at com.atm.xunit.hometask.runner.CalculatorTest.testCosine(CalculatorTest.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testCosine -->
  <testcase name="testDiv" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testDiv" time="0.0" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testDiv" time="0.0" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testCosine" time="0.006" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testMul" time="0.0" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testMul" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testCosine" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testMul" time="0.0" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegAdd" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegMul" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegMul" time="0.0" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegMul" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegAdd" time="0.006" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegSqrt" time="0.002" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegSqrt" time="0.002" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegAdd" time="0.005" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegSqrt" time="0.002" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testSub" time="0.002" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testSub" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testTangens" time="0.005" classname="com.atm.xunit.hometask.runner.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [1.6197751905438615] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [1.6197751905438615] but found [1.0]
	at com.atm.xunit.hometask.runner.CalculatorTest.testTangens(CalculatorTest.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testTangens -->
  <testcase name="testSub" time="0.002" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testTangent" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testTangent" time="0.001" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testTangent" time="0.0" classname="com.atm.xunit.hometask.runner.CalculatorTest"/>
  <testcase name="testNegDiv" time="0.0" classname="com.atm.xunit.hometask.runner.CalculatorTest">
    <ignored/>
  </testcase> <!-- testNegDiv -->
  <testcase name="testSqrt" time="0.0" classname="com.atm.xunit.hometask.runner.CalculatorTest">
    <ignored/>
  </testcase> <!-- testSqrt -->
</testsuite> <!-- CalculatorTest -->
